name: Accountant_2_0
description: A new Flutter project for managing expenses.

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.9.1
  table_calendar: ^3.0.0
  path_provider: ^2.0.11
  pdf: ^3.8.1
  shared_preferences: ^2.0.0
  # State management and database
  sqflite: ^2.0.0+3
  path: ^1.8.1

  # Charting library for graphical reports
  fl_chart: ^0.35.0

  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # Assets can be added here
  assets:
    - assets/logo.png
    - assets/budget_master.png
    - assets/consistent_tracker.png
    - assets/saving_star.png
